INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (1, 'ACT');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (2, 'ACT - Jens');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (3, 'ACT  RN/KS   1 Tripper');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (4, 'ACT - YENS');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (5, 'ACT - YENS             (5 OF 9)   SW');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (6, 'ACT - YENS  (7 OF 10)   KS       LA');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (7, 'ACT - YENS  (8 OF 10)   SM     LA');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (8, 'ACT - YENS ( 1 OF 2)   KS');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (9, 'ACT - YENS (1 of 2)  DL');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (10, 'ACT - YENS (2 OF 2) SM OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (11, 'ACT - YENS (2 OF 8) SM   OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (12, 'ACT - YENS (3 OF 10)  DS      OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (13, 'ACT - YENS (3 of 8) SM   OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (14, 'ACT - YENS (4 OF 10)   DL     OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (15, 'ACT - YENS (4 of 8) DL   OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (16, 'ACT - YENS (5 OF 10)   SM     OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (17, 'ACT - YENS (5 of 8)  SM   OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (18, 'ACT - YENS (7 OF 10)   DL   OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (19, 'ACT - YENS (8 OF 10)   SM     OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (20, 'ACT - YENS(1 of 1) KS   OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (21, 'ACT - YENS(7 of 8) KS   OAK');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (22, 'Allied');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (23, 'American Container Trading  RN/KS');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (24, 'Anercican Container Trading-Yens    RN');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (25, 'Antonio Soto (Old unit # 06-0611)');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (26, 'CGI');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (27, 'Compass Container - Paul');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (28, 'Conex');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (29, 'Constar charged to NCC Mobile Storage');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (30, 'Container Systems International     LB/J');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (31, 'Container Systems International  LB/BP/JN');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (32, 'David Flood');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (33, 'Dena Shrop');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (34, 'Jens - ACT     OAKLAND  (1 of 5 )');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (35, 'Jens - ACT    LA  (1 of  5)');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (36, 'Jens - ACT    LA  (2 of  5)');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (37, 'Jens - ACT    LA  (3 of  5)');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (38, 'Jens - ACT    LA  (4 of  5)');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (39, 'Joseph Keane');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (40, 'Ken Sorrinson');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (41, 'Luke Pankratz');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (42, 'Mario Montes      RN');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (43, 'Mario Montes   RN/KS         (2 of 4)');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (44, 'MSG - Converted to 50/50');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (45, 'NCC Mobile Storage Charge on account');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (46, 'NCC Owned');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (47, 'NCC Purchased from Mobile Storage');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (48, 'NCC Purchased from Mobile Storage Visa');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (49, 'OC');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (50, 'Purchased from Shropshire');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (51, 'Roger Tyler');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (52, 'Stan Baker');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (53, 'Trailer from freightliner');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (54, 'URI -641 OLD #07-0729');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (55, 'World Container Mart');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (56, 'World Container Mart    (1 of 2)');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (57, 'World Container Mart    (1 of 3)');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (58, 'World Container Mart    (2 of 3)');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (59, 'World Container Mart    (2 of 3)     JN 6/13');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (60, 'World Container Mart   (3 of 3)     JN   6/13');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (61, 'World Container Mart-Sam          KS');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (62, 'World Container Mart-Sam         BP');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (63, 'Yesenia');
INSERT INTO `vendors` (`vendor_ID`, `vendor_name`) VALUES (64, 'Yesenia Buskirk');
